# Generated by Django 3.0.3 on 2021-07-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervencionEst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_Inicio', models.DateField(verbose_name='Fecha de Ininicio de intervencion')),
                ('fecha_ultima', models.DateField(blank=True, null=True, verbose_name='Fecha de ultima sesión')),
                ('Num_Ses', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Numero de Sesiones')),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Intervención Estudiante',
                'verbose_name_plural': 'Intervenciones Estudiantes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SesionEst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha de Sesión')),
                ('IntervencionEst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervencion.IntervencionEst', verbose_name='Intervencion de Estudiante')),
            ],
            options={
                'verbose_name': 'Sesión Estudiante',
                'verbose_name_plural': 'Sesiones Estudiantes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SesionD9',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AC6', models.PositiveIntegerField(default=0, verbose_name='Completar líneas verticales trazadas en forma entrecortada')),
                ('AC7', models.PositiveIntegerField(default=0, verbose_name='Seguir laberintos trazando líneas verticales y horizontales')),
                ('AC8', models.PositiveIntegerField(default=0, verbose_name='Unir dos puntos para formas líneas verticales')),
                ('AC9', models.PositiveIntegerField(default=0, verbose_name='Punzar líneas verticales grandes y pequeñas')),
                ('AC10', models.PositiveIntegerField(default=0, verbose_name='Copiar en la pizarra o en el papel cuadriculado líneas verticales')),
                ('AC34', models.PositiveIntegerField(default=0, verbose_name='Completar líneas oblícuas trazadas en forma entrecortada')),
                ('AC35', models.PositiveIntegerField(default=0, verbose_name='Seguir laberintos trazando líneas oblicuas')),
                ('AC36', models.PositiveIntegerField(default=0, verbose_name='Unir dos puntos para formas líneas oblicuas')),
                ('AC37', models.PositiveIntegerField(default=0, verbose_name='Punzar líneas oblicuas grandes y pequeñas')),
                ('AC48', models.PositiveIntegerField(default=0, verbose_name='Copiar en la pizarra o en el papel cuadriculado líneas oblicuas')),
                ('AC39', models.PositiveIntegerField(default=0, verbose_name='Juegos')),
                ('AC40', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC41', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC42', models.PositiveIntegerField(default=0, verbose_name='Juegos serios con lápiz- libre - dos')),
                ('SesionEst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervencion.SesionEst', verbose_name='SesionEst')),
            ],
            options={
                'verbose_name': 'Sesion Destreza 9',
                'verbose_name_plural': 'Sesiones Destrezas 9',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SesionD8',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AC1', models.PositiveIntegerField(default=0, verbose_name='Completar líneas horizontales trazadas en forma entrecortada')),
                ('AC2', models.PositiveIntegerField(default=0, verbose_name='Seguir laberintos trazando líneas horizontales')),
                ('AC3', models.PositiveIntegerField(default=0, verbose_name='Unir dos puntos para formas líneas horizontales')),
                ('AC4', models.PositiveIntegerField(default=0, verbose_name='Punzar líneas horizontales grandes y pequeñas')),
                ('AC5', models.PositiveIntegerField(default=0, verbose_name='Copiar en la pizarra o en el papel cuadriculado líneas horizontales')),
                ('AC6', models.PositiveIntegerField(default=0, verbose_name='Completar líneas verticales trazadas en forma entrecortada')),
                ('AC7', models.PositiveIntegerField(default=0, verbose_name='Seguir laberintos trazando líneas verticales y horizontales')),
                ('AC8', models.PositiveIntegerField(default=0, verbose_name='Unir dos puntos para formas líneas verticales')),
                ('AC9', models.PositiveIntegerField(default=0, verbose_name='Punzar líneas verticales grandes y pequeñas')),
                ('AC10', models.PositiveIntegerField(default=0, verbose_name='Copiar en la pizarra o en el papel cuadriculado líneas verticales')),
                ('AC39', models.PositiveIntegerField(default=0, verbose_name='Juegos')),
                ('AC40', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC41', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC42', models.PositiveIntegerField(default=0, verbose_name='Juegos serios con lápiz- libre - dos')),
                ('SesionEst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervencion.SesionEst', verbose_name='Sesion Est')),
            ],
            options={
                'verbose_name': 'Sesion Destreza 8',
                'verbose_name_plural': 'Sesiones Destrezas 8',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SesionD7',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AC29', models.PositiveIntegerField(default=0, verbose_name='Completar líneas onduladas trazadas de forma entrecortada')),
                ('AC30', models.PositiveIntegerField(default=0, verbose_name='Seguir el trazo de los bucles ascendentes o descendentes')),
                ('AC31', models.PositiveIntegerField(default=0, verbose_name='Realizar ondas o blucles dentro de dos líneas, sobre ejes horizontales, verticales o inclinados')),
                ('AC32', models.PositiveIntegerField(default=0, verbose_name='Seguir el trazo de la letra /m/ /n/ manuscrita en forma continua')),
                ('AC39', models.PositiveIntegerField(default=0, verbose_name='Juegos')),
                ('AC40', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC41', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC42', models.PositiveIntegerField(default=0, verbose_name='Juegos serios con lápiz- libre - dos')),
                ('SesionEst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervencion.SesionEst', verbose_name='Sesion Est')),
            ],
            options={
                'verbose_name': 'Sesion Destreza 7',
                'verbose_name_plural': 'Sesiones Destrezas 7',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SesionD6',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AC25', models.PositiveIntegerField(default=0, verbose_name='Completar los triángulos trazados en forma entrecortada')),
                ('AC26', models.PositiveIntegerField(default=0, verbose_name='Punzar siguiendo el trazo del triángulo')),
                ('AC27', models.PositiveIntegerField(default=0, verbose_name='Unir los puntos para formar el triángulo')),
                ('AC28', models.PositiveIntegerField(default=0, verbose_name='Seguir los caminos en zig-zag')),
                ('AC39', models.PositiveIntegerField(default=0, verbose_name='Juegos')),
                ('AC40', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC41', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC42', models.PositiveIntegerField(default=0, verbose_name='Juegos serios con lápiz- libre - dos')),
                ('SesionEst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervencion.SesionEst', verbose_name='SesionEst')),
            ],
            options={
                'verbose_name': 'Sesion Destreza 6',
                'verbose_name_plural': 'Sesiones Destrezas 6',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SesionD5',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AC21', models.PositiveIntegerField(default=0, verbose_name='Copiar en la pizarra o papel cuadriculado una cruz')),
                ('AC22', models.PositiveIntegerField(default=0, verbose_name='Unir los puntos trazados para formar una cruz')),
                ('AC23', models.PositiveIntegerField(default=0, verbose_name='Completar las cruces dibujadas de forma entrecortada')),
                ('AC24', models.PositiveIntegerField(default=0, verbose_name='Punzar las cruces dibujadas')),
                ('AC39', models.PositiveIntegerField(default=0, verbose_name='Juegos')),
                ('AC40', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC41', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC42', models.PositiveIntegerField(default=0, verbose_name='Juegos serios con lápiz- libre - dos')),
                ('SesionEst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervencion.SesionEst', verbose_name='SesionEst')),
            ],
            options={
                'verbose_name': 'Sesion Destreza 5',
                'verbose_name_plural': 'Sesiones Destrezas 5',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SesionD4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AC16', models.PositiveIntegerField(default=0, verbose_name='Completar los cuadrados trazados en forma entrecortada')),
                ('AC17', models.PositiveIntegerField(default=0, verbose_name='Punzar siguiendo el trazo del cuadrado')),
                ('AC18', models.PositiveIntegerField(default=0, verbose_name='Unir los puntos para formar el cuadrado')),
                ('AC19', models.PositiveIntegerField(default=0, verbose_name='Seguir caminos trazados en forma de L')),
                ('AC20', models.PositiveIntegerField(default=0, verbose_name='Trazar el cuadrado en el papel cuadriculado')),
                ('AC39', models.PositiveIntegerField(default=0, verbose_name='Juegos')),
                ('AC40', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC41', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC42', models.PositiveIntegerField(default=0, verbose_name='Juegos serios con lápiz- libre - dos')),
                ('SesionEst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervencion.SesionEst', verbose_name='SesionEst')),
            ],
            options={
                'verbose_name': 'Sesion Destreza 4',
                'verbose_name_plural': 'Sesiones Destrezas 4',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SesionD3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AC11', models.PositiveIntegerField(default=0, verbose_name='Completar los círculos trazados de forma entrecortada')),
                ('AC12', models.PositiveIntegerField(default=0, verbose_name='Completar los semicírculos trazados de forma entrecortada')),
                ('AC13', models.PositiveIntegerField(default=0, verbose_name='Punzar siguiendo el trazo del círculo')),
                ('AC14', models.PositiveIntegerField(default=0, verbose_name='Unir los puntos para formar el círculo')),
                ('AC15', models.PositiveIntegerField(default=0, verbose_name='Seguir el contorno de  bucles ascendentes y descendentes')),
                ('AC41', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC42', models.PositiveIntegerField(default=0, verbose_name='Juegos serios con lápiz- libre - dos')),
                ('SesionEst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervencion.SesionEst', verbose_name='SesionEst')),
            ],
            options={
                'verbose_name': 'Sesion Destreza 3',
                'verbose_name_plural': 'Sesiones Destrezas 3',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SesionD2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AC6', models.PositiveIntegerField(default=0, verbose_name='Completar líneas verticales trazadas en forma entrecortada')),
                ('AC7', models.PositiveIntegerField(default=0, verbose_name='Seguir laberintos trazando líneas verticales y horizontales')),
                ('AC8', models.PositiveIntegerField(default=0, verbose_name='Unir dos puntos para formas líneas verticales')),
                ('AC9', models.PositiveIntegerField(default=0, verbose_name='Punzar líneas verticales grandes y pequeñas')),
                ('AC10', models.PositiveIntegerField(default=0, verbose_name='Copiar en la pizarra o en el papel cuadriculado líneas verticales')),
                ('AC41', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC42', models.PositiveIntegerField(default=0, verbose_name='Juegos serios con lápiz- libre - dos')),
                ('SesionEst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervencion.SesionEst', verbose_name='SesionEst')),
            ],
            options={
                'verbose_name': 'Sesion Destreza 2',
                'verbose_name_plural': 'Sesiones Destrezas 2',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SesionD1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AC1', models.PositiveIntegerField(default=0, verbose_name='Completar líneas horizontales trazadas en forma entrecortada')),
                ('AC2', models.PositiveIntegerField(default=0, verbose_name='Seguir laberintos trazando líneas horizontales')),
                ('AC3', models.PositiveIntegerField(default=0, verbose_name='Unir dos puntos para formas líneas horizontales')),
                ('AC4', models.PositiveIntegerField(default=0, verbose_name='Punzar líneas horizontales grandes y pequeñas')),
                ('AC5', models.PositiveIntegerField(default=0, verbose_name='Copiar en la pizarra o en el papel cuadriculado líneas horizontales')),
                ('AC41', models.PositiveIntegerField(default=0, verbose_name='Dos actividades')),
                ('AC42', models.PositiveIntegerField(default=0, verbose_name='Juegos serios con lápiz- libre - dos')),
                ('comportamiento', models.CharField(choices=[('Logrado', 'Logrado'), ('En vias de logro', 'En proceso'), ('No logrado', 'No logrado')], default='En vias de logro', max_length=20, verbose_name='Comportamniento de estudiante en sesión')),
                ('SesionEst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intervencion.SesionEst', verbose_name='Sesion de Estudiante')),
            ],
            options={
                'verbose_name': 'Sesion Destreza 1',
                'verbose_name_plural': 'Sesiones Destrezas 1',
                'ordering': ['-id'],
            },
        ),
    ]
