# Generated by Django 3.0.3 on 2021-07-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('edad_Cronologica', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Edad Cronologica')),
                ('edad_Mental', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Edad Mental')),
                ('grado_Educacion', models.CharField(choices=[('No Escolarizado', 'No Escolarizado'), ('Educacion Inicial', 'Educacion Inicial'), ('Educacion Basica', 'Educacion Basica')], default='Educacion Inicial', max_length=50, verbose_name='Grado de Educacionn')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disc_intelectual_grado', models.CharField(choices=[('No presenta', 'No presenta'), ('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Severo', 'Severo'), ('Profundo', 'Profundo')], default='No presenta', max_length=50, verbose_name='Discapacidad Intelectual')),
                ('disc_visual_grado', models.CharField(choices=[('No presenta', 'No presenta'), ('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Severo', 'Severo'), ('Total', 'Total')], default='No presenta', max_length=50, verbose_name='Discapacidad Visual')),
                ('disc_motriz_grado', models.CharField(choices=[('No presenta', 'No presenta'), ('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Severo', 'Severo')], default='No presenta', max_length=50)),
                ('disc_auditiva_grado', models.CharField(choices=[('No presenta', 'No presenta'), ('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Severo', 'Severo'), ('Profundo', 'Profundo')], default='No presenta', max_length=50)),
                ('disc_auditiva_profundidad', models.CharField(choices=[('No presenta', 'No presenta'), ('Unilateral', 'Unilateral'), ('Bilateral', 'Bilatera')], default='No presenta', max_length=50)),
                ('disc_pci_grado', models.CharField(choices=[('No presenta', 'No presenta'), ('Espástica', 'Espástica'), ('Atetósica', 'Atetósica'), ('Atáxica', 'Atáxica'), ('Mixta', 'Mixta ')], default='No presenta', max_length=50)),
                ('disc_pci_profundidad', models.CharField(choices=[('No presenta', 'No presenta'), ('Monoplejía', 'Monoplejía'), ('Hemiplejía', 'Hemiplejía'), ('Paraplejía', 'Paraplejía'), ('Triplejía', 'Triplejía'), ('Tetraplejía', 'Tetraplejía')], default='No presenta', max_length=50)),
                ('sindrome_down', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('sindrome_lennon', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('sindrome_te', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('sindorme_tdah', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('transtorno_agresivo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('control_cuerpo', models.CharField(choices=[('A1', 'Mantiene el control total de su cuerpo'), ('A2', 'Mantiene el control de su cuerpo con dificultad en el equilibrio y le gustan las actividades de motricidad gruesa'), ('A3', 'Mantiene el control de su cuerpo con dificultad en el equilibrio y no le gustan las actividades de motricidad gruesa'), ('A4', 'Mantiene el control de su cuerpo, pero le cuesta realizar actividades de motricidad gruesa'), ('A5', 'No mantiene el control de su cuerpo, necesita apoyo y supervisión total')], default='A1', max_length=2)),
                ('cord_oculo_manual', models.CharField(choices=[('B1', 'Buena coordinación óculo manual'), ('B2', 'Dificultad en mantener la coordinación óculo manual')], default='B1', max_length=2)),
                ('atencion', models.CharField(choices=[('C1', 'Mantiene la atención durante una tarea asignada'), ('C2', 'Mantiene la atención durante una tarea asignada a pesar que se demora, pero la culmina'), ('C3', 'La mayoría de las veces mantiene la atención en una tarea asignada'), ('C4', 'Le cuesta mantener la atención en una tarea asignada, se distrae con facilidad'), ('C5', 'Le cuesta mantener la atención en una tarea asignada, quiere terminarla rápido'), ('C6', 'Mantiene la atención por períodos cortos en objetos con luces y sonidos')], default='C1', max_length=2)),
                ('lateralidad', models.CharField(choices=[('D1', 'Definida'), ('D2', 'Cambia de mano constantemente al realizar una actividad'), ('D3', 'Cambia de mano en pocas ocasiones, pero utiliza más una mano')], default='D1', max_length=2)),
                ('disociacion_manos', models.CharField(choices=[('E1', 'Utiliza constantemente la mano de apoyo'), ('E2', 'Utiliza a veces la mano de apoyo'), ('E3', 'No utiliza la mano de apoyo')], default='E1', max_length=2)),
                ('predispo_mesa', models.CharField(choices=[('F1', 'Permanece sentado durante una tarea'), ('F2', 'Le cuesta mantenerse sentado en una tarea'), ('F3', 'No permanece sentado')], default='F1', max_length=2)),
                ('manipulacion_lapiz', models.CharField(choices=[('G1', 'Le atraen los lápices y los manipula'), ('G2', 'Le atraen poco los lápices y los manipula poco'), ('G3', 'No le atraen los lápices ni los manipula'), ('G4', 'No le atraen los lápices ni los manipula a menos de que sean necesarios en la tarea asignada')], default='G1', max_length=2)),
                ('sensibilidad_tacto', models.CharField(choices=[('H1', 'Tolera actividades que implican ensuciarse y mojarse las manos'), ('H2', 'Tolera poco las actividades que implican ensuciarse o mojarse las manos'), ('H3', 'No tolera actividades que implican ensuciarse o mojarse las manos')], default='H1', max_length=2)),
                ('lenguaje_compresivo', models.CharField(choices=[('A1', 'Tiene buena comprensión'), ('A2', 'Su comprensión es buena, pero necesita de apoyos visuales y señas'), ('A3', 'Su comprensión es regular, hay que repetirle algunas veces la consigna'), ('A4', 'Su comprensión es regular a pesar de repetirle verbalmente necesita de apoyos visuales.'), ('A5', 'Su comprensión es mala, responde por reflejos')], default='A1', max_length=2)),
                ('lenguaje_expresivo', models.CharField(choices=[('B1', 'Tiene buen lenguaje expresivo'), ('B2', 'Su lenguaje es claro, rígido, repetitivo y le cuesta participar en conversaciones'), ('B3', 'Se expresa mediante el lenguaje oral con una cierta distorsión en la entonación de la voz'), ('B4', 'Se expresa mediante sonidos guturales, gritos y llanto'), ('B5', 'Se expresa mediante lenguaje oral, pero tiene dificultad en pronunciar claramente'), ('B6', 'Se expresa mediante lenguaje oral con palabras monosílabas y bisílabas'), ('B7', 'Se expresa mediante Sistemas Alternativos y Aumentativos de Comunicación (pictogramas)'), ('B8', 'Se expresa mediante lenguaje de señas y Sistemas Alternativos y Aumentativos de Comunicación')], default='B1', max_length=2)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante')),
            ],
        ),
    ]
