# Generated by Django 3.0.3 on 2021-10-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=10, verbose_name='Sexo'),
        ),
    ]
