# Generated by Django 2.2.10 on 2022-01-05 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_estudiante_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('cedula', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Terapeuta', verbose_name='Terapeuta'),
        ),
    ]
