# Generated by Django 3.0.3 on 2022-03-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0004_auto_20220307_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='Terapeuta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Terapeuta', verbose_name='Terapeuta'),
        ),
    ]
