# Generated by Django 3.0.3 on 2021-09-29 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('serial', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='serial')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Sesion')),
                ('area', models.CharField(choices=[('Motricidad Gruesa', 'Motricidad Gruesa'), ('Preescritura', 'Preescritura'), ('Escritura', 'Escritura')], default='Motricidad Gruesa', max_length=60, verbose_name='Area')),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'sesion',
                'verbose_name_plural': 'sesiones',
            },
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Actividad', models.CharField(max_length=100, verbose_name='Tipo Acividad')),
                ('Tiempo', models.CharField(max_length=20, verbose_name='Tiempo de Acividad')),
                ('Errores', models.PositiveIntegerField(verbose_name='Numero de Errores')),
                ('datos', models.CharField(max_length=20, verbose_name='Datos recibidos')),
                ('Sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.Sesion', verbose_name='Sesion de Intervencion')),
            ],
            options={
                'verbose_name': 'Actividad Tablero',
                'verbose_name_plural': 'Actividades Tablero',
            },
        ),
    ]
