# Generated by Django 3.0.3 on 2021-07-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante', verbose_name='Estudiante Evaluado')),
            ],
            options={
                'verbose_name': 'Evaluacion Estudiante',
                'verbose_name_plural': 'Evaluaciones Estudiantes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionD9',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('D9', models.CharField(choices=[('Logrado', 'Logrado'), ('En vias de logro', 'En proceso'), ('No logrado', 'No logrado')], default='Logrado', max_length=20, verbose_name='PENDIENTE NUMEROS')),
                ('D10', models.CharField(choices=[('Normal', 'Normal'), ('Hipertónico', 'Hipertónico'), ('Hipotónico', 'Hipotónico')], default='Normal', max_length=20, verbose_name='PRESION SOBRE EL PAPEL')),
                ('D11', models.CharField(choices=[('Tridigital', 'Tridigital'), ('Digital', 'Digital'), ('Modal', 'Modal')], default='Tridigital', max_length=20, verbose_name='TIPO DE AGARRE')),
                ('D12', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=20, verbose_name='DIRECCIONALIDAD')),
                ('D13', models.CharField(choices=[('No estresado', 'No estresado'), ('Estresado', 'Estresado')], default='No estresado', max_length=20, verbose_name='ESTADO DE ANIMO')),
                ('D14', models.CharField(choices=[('Pronacion supinacion', 'Pronacion supinacion'), ('Movimiento Palmar', 'Movimiento Palmar')], default='Pronacion supinacion', max_length=20, verbose_name='MOVIMIENTO MANO DEDOS')),
                ('EvaluacionD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.EvaluacionD', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Evaluacion Destreza 9',
                'verbose_name_plural': 'Evaluaciones Destreza 9',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionD8',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('D8', models.CharField(choices=[('Logrado', 'Logrado'), ('En vias de logro', 'En proceso'), ('No logrado', 'No logrado')], default='Logrado', max_length=20, verbose_name='PENDIENTE LETRAS')),
                ('D10', models.CharField(choices=[('Normal', 'Normal'), ('Hipertónico', 'Hipertónico'), ('Hipotónico', 'Hipotónico')], default='Normal', max_length=20, verbose_name='PRESION SOBRE EL PAPEL')),
                ('D11', models.CharField(choices=[('Tridigital', 'Tridigital'), ('Digital', 'Digital'), ('Modal', 'Modal')], default='Tridigital', max_length=20, verbose_name='TIPO DE AGARRE')),
                ('D12', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=20, verbose_name='DIRECCIONALIDAD')),
                ('D13', models.CharField(choices=[('No estresado', 'No estresado'), ('Estresado', 'Estresado')], default='No estresado', max_length=20, verbose_name='ESTADO DE ANIMO')),
                ('D14', models.CharField(choices=[('Pronacion supinacion', 'Pronacion supinacion'), ('Movimiento Palmar', 'Movimiento Palmar')], default='Pronacion supinacion', max_length=20, verbose_name='MOVIMIENTO MANO DEDOS')),
                ('EvaluacionD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.EvaluacionD', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Evaluacion Destreza 8',
                'verbose_name_plural': 'Evaluaciones Destreza 8',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionD7',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('D7', models.CharField(choices=[('Logrado', 'Logrado'), ('En vias de logro', 'En proceso'), ('No logrado', 'No logrado')], default='Logrado', max_length=20, verbose_name='DIBUJA ONDULADA')),
                ('D10', models.CharField(choices=[('Normal', 'Normal'), ('Hipertónico', 'Hipertónico'), ('Hipotónico', 'Hipotónico')], default='Normal', max_length=20, verbose_name='PRESION SOBRE EL PAPEL')),
                ('D11', models.CharField(choices=[('Tridigital', 'Tridigital'), ('Digital', 'Digital'), ('Modal', 'Modal')], default='Tridigital', max_length=20, verbose_name='TIPO DE AGARRE')),
                ('D12', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=20, verbose_name='DIRECCIONALIDAD')),
                ('D13', models.CharField(choices=[('No estresado', 'No estresado'), ('Estresado', 'Estresado')], default='No estresado', max_length=20, verbose_name='ESTADO DE ANIMO')),
                ('D14', models.CharField(choices=[('Pronacion supinacion', 'Pronacion supinacion'), ('Movimiento Palmar', 'Movimiento Palmar')], default='Pronacion supinacion', max_length=20, verbose_name='MOVIMIENTO MANO DEDOS')),
                ('EvaluacionD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.EvaluacionD', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Evaluacion Destreza 7',
                'verbose_name_plural': 'Evaluaciones Destreza 7',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionD6',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('D6', models.CharField(choices=[('Logrado', 'Logrado'), ('En vias de logro', 'En proceso'), ('No logrado', 'No logrado')], default='Logrado', max_length=20, verbose_name='DIBUJA TRIANGULO')),
                ('D10', models.CharField(choices=[('Normal', 'Normal'), ('Hipertónico', 'Hipertónico'), ('Hipotónico', 'Hipotónico')], default='Normal', max_length=20, verbose_name='PRESION SOBRE EL PAPEL')),
                ('D11', models.CharField(choices=[('Tridigital', 'Tridigital'), ('Digital', 'Digital'), ('Modal', 'Modal')], default='Tridigital', max_length=20, verbose_name='TIPO DE AGARRE')),
                ('D12', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=20, verbose_name='DIRECCIONALIDAD')),
                ('D13', models.CharField(choices=[('No estresado', 'No estresado'), ('Estresado', 'Estresado')], default='No estresado', max_length=20, verbose_name='ESTADO DE ANIMO')),
                ('D14', models.CharField(choices=[('Pronacion supinacion', 'Pronacion supinacion'), ('Movimiento Palmar', 'Movimiento Palmar')], default='Pronacion supinacion', max_length=20, verbose_name='MOVIMIENTO MANO DEDOS')),
                ('EvaluacionD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.EvaluacionD', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Evaluacion Destreza 6',
                'verbose_name_plural': 'Evaluaciones Destreza 6',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionD5',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('D5', models.CharField(choices=[('Logrado', 'Logrado'), ('En vias de logro', 'En proceso'), ('No logrado', 'No logrado')], default='Logrado', max_length=20, verbose_name='DIBUJA CRUZ')),
                ('D10', models.CharField(choices=[('Normal', 'Normal'), ('Hipertónico', 'Hipertónico'), ('Hipotónico', 'Hipotónico')], default='Normal', max_length=20, verbose_name='PRESION SOBRE EL PAPEL')),
                ('D11', models.CharField(choices=[('Tridigital', 'Tridigital'), ('Digital', 'Digital'), ('Modal', 'Modal')], default='Tridigital', max_length=20, verbose_name='TIPO DE AGARRE')),
                ('D12', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=20, verbose_name='DIRECCIONALIDAD')),
                ('D13', models.CharField(choices=[('No estresado', 'No estresado'), ('Estresado', 'Estresado')], default='No estresado', max_length=20, verbose_name='ESTADO DE ANIMO')),
                ('D14', models.CharField(choices=[('Pronacion supinacion', 'Pronacion supinacion'), ('Movimiento Palmar', 'Movimiento Palmar')], default='Pronacion supinacion', max_length=20, verbose_name='MOVIMIENTO MANO DEDOS')),
                ('EvaluacionD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.EvaluacionD', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Evaluacion Destreza 5',
                'verbose_name_plural': 'Evaluaciones Destreza 5',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionD4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('D4', models.CharField(choices=[('Logrado', 'Logrado'), ('En vias de logro', 'En proceso'), ('No logrado', 'No logrado')], default='Logrado', max_length=20, verbose_name='DIBUJA CUADRADO')),
                ('D10', models.CharField(choices=[('Normal', 'Normal'), ('Hipertónico', 'Hipertónico'), ('Hipotónico', 'Hipotónico')], default='Normal', max_length=20, verbose_name='PRESION SOBRE EL PAPEL')),
                ('D11', models.CharField(choices=[('Tridigital', 'Tridigital'), ('Digital', 'Digital'), ('Modal', 'Modal')], default='Tridigital', max_length=20, verbose_name='TIPO DE AGARRE')),
                ('D12', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=20, verbose_name='DIRECCIONALIDAD')),
                ('D13', models.CharField(choices=[('No estresado', 'No estresado'), ('Estresado', 'Estresado')], default='No estresado', max_length=20, verbose_name='ESTADO DE ANIMO')),
                ('D14', models.CharField(choices=[('Pronacion supinacion', 'Pronacion supinacion'), ('Movimiento Palmar', 'Movimiento Palmar')], default='Pronacion supinacion', max_length=20, verbose_name='MOVIMIENTO MANO DEDOS')),
                ('EvaluacionD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.EvaluacionD', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Evaluacion Destreza 4',
                'verbose_name_plural': 'Evaluaciones Destreza 4',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionD3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('D3', models.CharField(choices=[('Logrado', 'Logrado'), ('En vias de logro', 'En proceso'), ('No logrado', 'No logrado')], default='Logrado', max_length=20, verbose_name='DIBUJA CIRCUNFERENCIA')),
                ('D10', models.CharField(choices=[('Normal', 'Normal'), ('Hipertónico', 'Hipertónico'), ('Hipotónico', 'Hipotónico')], default='Normal', max_length=20, verbose_name='PRESION SOBRE EL PAPEL')),
                ('D11', models.CharField(choices=[('Tridigital', 'Tridigital'), ('Digital', 'Digital'), ('Modal', 'Modal')], default='Tridigital', max_length=20, verbose_name='TIPO DE AGARRE')),
                ('D12', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=20, verbose_name='DIRECCIONALIDAD')),
                ('D13', models.CharField(choices=[('No estresado', 'No estresado'), ('Estresado', 'Estresado')], default='No estresado', max_length=20, verbose_name='ESTADO DE ANIMO')),
                ('D14', models.CharField(choices=[('Pronacion supinacion', 'Pronacion supinacion'), ('Movimiento Palmar', 'Movimiento Palmar')], default='Pronacion supinacion', max_length=20, verbose_name='MOVIMIENTO MANO DEDOS')),
                ('EvaluacionD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.EvaluacionD', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Evaluacion Destreza 3',
                'verbose_name_plural': 'Evaluaciones Destreza 3',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionD2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('D2', models.CharField(choices=[('Logrado', 'Logrado'), ('En vias de logro', 'En proceso'), ('No logrado', 'No logrado')], default='Logrado', max_length=20, verbose_name='DIBUJA LINEA VERTICAL')),
                ('D10', models.CharField(choices=[('Normal', 'Normal'), ('Hipertónico', 'Hipertónico'), ('Hipotónico', 'Hipotónico')], default='Normal', max_length=20, verbose_name='PRESION SOBRE EL PAPEL')),
                ('D11', models.CharField(choices=[('Tridigital', 'Tridigital'), ('Digital', 'Digital'), ('Modal', 'Modal')], default='Tridigital', max_length=20, verbose_name='TIPO DE AGARRE')),
                ('D12', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=20, verbose_name='DIRECCIONALIDAD')),
                ('D13', models.CharField(choices=[('No estresado', 'No estresado'), ('Estresado', 'Estresado')], default='No estresado', max_length=20, verbose_name='ESTADO DE ANIMO')),
                ('D14', models.CharField(choices=[('Pronacion supinacion', 'Pronacion supinacion'), ('Movimiento Palmar', 'Movimiento Palmar')], default='Pronacion supinacion', max_length=20, verbose_name='MOVIMIENTO MANO DEDOS')),
                ('EvaluacionD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.EvaluacionD', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Evaluacion Destreza 2',
                'verbose_name_plural': 'Evaluaciones Destreza 2',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionD1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('D1', models.CharField(choices=[('Logrado', 'Logrado'), ('En vias de logro', 'En vias de logro'), ('No logrado', 'No logrado')], default='Logrado', max_length=20, verbose_name='DIBUJA LINEA HORIZONTAL')),
                ('D10', models.CharField(choices=[('Normal', 'Normal'), ('Hipertónico', 'Hipertónico'), ('Hipotónico', 'Hipotónico')], default='Normal', max_length=20, verbose_name='PRESION SOBRE EL PAPEL')),
                ('D11', models.CharField(choices=[('Tridigital', 'Tridigital'), ('Digital', 'Digital'), ('Modal', 'Modal')], default='Tridigital', max_length=20, verbose_name='TIPO DE AGARRE')),
                ('D12', models.CharField(choices=[('Buena', 'Buena'), ('Mala', 'Mala')], default='Buena', max_length=20, verbose_name='DIRECCIONALIDAD')),
                ('D13', models.CharField(choices=[('No estresado', 'No estresado'), ('Estresado', 'Estresado')], default='No estresado', max_length=20, verbose_name='ESTADO DE ANIMO')),
                ('D14', models.CharField(choices=[('Pronacion supinacion', 'Pronacion supinacion'), ('Movimiento Palmar', 'Movimiento Palmar')], default='Pronacion supinacion', max_length=20, verbose_name='MOVIMIENTO MANO DEDOS')),
                ('EvaluacionD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.EvaluacionD', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Evaluacion Destreza 1',
                'verbose_name_plural': 'Evaluaciones Destreza 1',
                'ordering': ['-id'],
            },
        ),
    ]
