# Generated by Django 2.2.10 on 2022-01-05 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_estudiante_sexo'),
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serios',
            name='tiempo',
        ),
        migrations.AddField(
            model_name='serios',
            name='Estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='serios',
            name='actividad',
            field=models.CharField(max_length=30, null=True, verbose_name='actividad'),
        ),
        migrations.AddField(
            model_name='serios',
            name='fecha',
            field=models.CharField(max_length=15, null=True, verbose_name='fecha'),
        ),
    ]
