# Generated by Django 3.0.3 on 2022-05-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_auto_20220105_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('mac', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='mac')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Desactivo', 'Desactivo')], default='Desactivo', max_length=10, verbose_name='Estado')),
                ('bateria', models.CharField(max_length=4, verbose_name='Bateria')),
            ],
        ),
    ]
